service: backend-sls
frameworkVersion: '>=4.0.0'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  environment:
    USE_DB_MOCK: ${env:USE_DB_MOCK}
    API_KEY: ${env:API_KEY}
    SUPABASE_URL_LIGA: ${env:SUPABASE_URL_LIGA}
    SUPABASE_SERVICE_ROLE_KEY_LIGA: ${env:SUPABASE_SERVICE_ROLE_KEY_LIGA}
    SMTP_HOST: ${env:SMTP_HOST}
    SMTP_PORT: ${env:SMTP_PORT}
    SMTP_USER: ${env:SMTP_USER}
    SMTP_PASS: ${env:SMTP_PASS}
    SMTP_SECURE: ${env:SMTP_SECURE}
    SMTP_FROM: ${env:SMTP_FROM}
    FRONTEND_URL: ${env:FRONTEND_URL}
    MOCK_EMAIL: ${env:MOCK_EMAIL}
    # Variables Webpay (Mapeadas desde .env)
    WEBPAY_HOST: ${env:WEBPAY_HOST}
    WEBPAY_API_KEY: ${env:WEBPAY_API_KEY}
    WEBPAY_COMMERCE_CODE: ${env:WEBPAY_COMMERCE_CODE}

  httpApi:
    cors:
      allowedOrigins:
        - '*'                # todos los orígenes
      allowedHeaders:
        - '*' 
      allowedMethods:
        - '*'  
      allowCredentials: false
      
functions:
  - ${file(./routes/login/serverlessLogin.yml)}
  - ${file(./routes/clubes/serverlessClubes.yml)}
  - ${file(./routes/jugadores/serverlessJugadores.yml)}
  - ${file(./routes/finanzas/serverlessFinanzas.yml)}
  - ${file(./routes/dashboard/serverlessDashboard.yml)}
  - ${file(./routes/categorias/serverlessCategorias.yml)}
  - ${file(./routes/eventos/serverlessEventos.yml)}
  - ${file(./routes/notifications/serverlessNotifications.yml)}
  - ${file(./routes/membresia/serverlessMembresia.yml)}
  - ${file(./routes/pagos/serverlessPagos.yml)}

plugins:
  - serverless-offline
  

package:
  individually: true
  exclude:
    - node_modules/**
    - .serverless/**
    - .webpack/**
    - logs/**
    - tmp/**
    - data/**
    - "**/*.map"
    - "**/*.zip"
    - "**/*.md"
    - "**/*.log"




build:
  esbuild:
    bundle: true
    minify: true
    target: node22
    platform: node
    external:
      - aws-sdk
    banner:
      js: "import { createRequire } from 'module'; const require = createRequire(import.meta.url);"

custom:
  serverless-offline:
    disableCookieValidation: true
    noPrependStage: true
      
